/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "addition.h"

bool_t
xdr_ADDITION (XDR *xdrs, ADDITION *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}
