/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "addition.h"

struct ADDITION *
add_proc_1_svc(struct ADDITION *argp, struct svc_req *rqstp)
{
	static struct ADDITION result;

	/*
	 * insert server code here
	 */

 	result.result = argp->arg1 + argp->arg2;
	
	return &result;
}
