/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADDITION_H_RPCGEN
#define _ADDITION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define ADD 0

struct ADDITION {
	float arg1;
	float arg2;
	float result;
};
typedef struct ADDITION ADDITION;

#define ADD_PROG 0x20000001
#define ADD_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD_PROC 1
extern  struct ADDITION * add_proc_1(struct ADDITION *, CLIENT *);
extern  struct ADDITION * add_proc_1_svc(struct ADDITION *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD_PROC 1
extern  struct ADDITION * add_proc_1();
extern  struct ADDITION * add_proc_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ADDITION (XDR *, ADDITION*);

#else /* K&R C */
extern bool_t xdr_ADDITION ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADDITION_H_RPCGEN */
